"""
reporting/markdown_gen.py — Markdown report generator for AEGIS

Generates a TryHackMe/writeup-style Markdown report, suitable
for GitHub, Obsidian notes, or portfolio documentation.
"""

import os
import logging
from datetime import datetime

logger = logging.getLogger("aegis")


def generate_markdown(scan_result: dict, output_path: str) -> str:
    """
    Build a Markdown report from ScanResult and save it.

    Returns:
        output_path (confirmed written)
    """
    meta = scan_result.get("meta", {})
    target = meta.get("target", "Unknown")
    date = meta.get("scan_start", datetime.now().isoformat())[:10]
    profile = meta.get("profile", "full")
    duration = meta.get("duration_seconds", 0)
    ai = scan_result.get("ai", {})
    risk = ai.get("risk_level", "Unknown")

    lines = []

    # ── Header ─────────────────────────────────────────
    lines += [
        "# AEGIS Vulnerability Assessment Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Date:** {date}  ",
        f"**Profile:** {profile}  ",
        f"**Duration:** {duration:.0f}s  ",
        f"**Risk Level:** {risk}  ",
        f"**Generated by:** AEGIS v1.0  ",
        "",
        "> ⚠️ This report is confidential and for authorized use only.",
        "",
        "---",
        "",
    ]

    # ── Executive Summary ──────────────────────────────
    lines += ["## Executive Summary", ""]
    summary = ai.get("executive_summary")
    if summary:
        lines += [summary, ""]
    else:
        lines += [
            "_AI analysis was not available. See raw scan data in the appendix._",
            "",
        ]
    lines += ["---", ""]

    # ── Findings ───────────────────────────────────────
    findings = ai.get("findings", [])
    if findings:
        lines += ["## Vulnerability Findings", ""]
        sev_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
        sorted_findings = sorted(
            findings,
            key=lambda f: sev_order.get(f.get("severity", "Low"), 3),
        )
        for i, f in enumerate(sorted_findings, 1):
            sev = f.get("severity", "Low")
            sev_icon = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🔵"}.get(sev, "⚪")
            lines += [
                f"### {i}. {f.get('title', 'Finding')} — {sev_icon} {sev}",
                "",
                f.get("description", ""),
                "",
                f"**Recommendation:** {f.get('recommendation', '')}",
                "",
                "---",
                "",
            ]

    # ── CVEs ────────────────────────────────────────────
    cves = ai.get("cves", [])
    if cves:
        lines += ["## CVE Findings", ""]
        lines += ["| CVE ID | CVSS | Service | Description | Recommendation |"]
        lines += ["|--------|------|---------|-------------|----------------|"]
        for cve in cves:
            desc = (cve.get("description") or "").replace("|", "/")[:80]
            rec = (cve.get("recommendation") or "").replace("|", "/")[:60]
            lines.append(
                f"| {cve.get('id','')} "
                f"| {cve.get('cvss','')} "
                f"| {cve.get('service','')} "
                f"| {desc} "
                f"| {rec} |"
            )
        lines += ["", "---", ""]

    # ── ATT&CK TTPs ────────────────────────────────────
    ttps = ai.get("ttps", [])
    if ttps:
        lines += ["## MITRE ATT&CK TTPs", ""]
        lines += ["| TTP ID | Name | Tactic |"]
        lines += ["|--------|------|--------|"]
        for ttp in ttps:
            lines.append(
                f"| {ttp.get('id','')} "
                f"| {ttp.get('name','')} "
                f"| {ttp.get('tactic','')} |"
            )
        lines += ["", "---", ""]

    # ── Open Ports ─────────────────────────────────────
    open_ports = scan_result.get("nmap", {}).get("open_ports", [])
    if open_ports:
        lines += ["## Open Ports (nmap)", ""]
        os_guess = scan_result.get("nmap", {}).get("os_guess")
        if os_guess:
            lines += [f"**OS Guess:** {os_guess}", ""]
        lines += ["| Port | Protocol | Service | Version |"]
        lines += ["|------|----------|---------|---------|"]
        for p in open_ports:
            lines.append(
                f"| {p.get('port','')} "
                f"| {p.get('protocol','')} "
                f"| {p.get('service','')} "
                f"| {p.get('version', '')} |"
            )
        lines += ["", "---", ""]

    # ── Service Probe Results ──────────────────────────
    lines += ["## Service Probe Results", ""]

    ftp = scan_result.get("ftp", {})
    if ftp.get("enabled"):
        lines += [
            "### FTP",
            f"- Anonymous Login: **{'YES ⚠️' if ftp.get('anonymous_login') else 'NO'}**",
        ]
        if ftp.get("banner"):
            lines.append(f"- Banner: `{ftp['banner']}`")
        if ftp.get("known_cves"):
            lines.append(f"- CVEs: {', '.join(ftp['known_cves'])}")
        if ftp.get("notes"):
            lines.append(f"- Notes: {ftp['notes']}")
        lines.append("")

    ssh = scan_result.get("ssh", {})
    if ssh.get("enabled"):
        lines += ["### SSH"]
        if ssh.get("version"):
            lines.append(f"- Version: `{ssh['version']}`")
        if ssh.get("known_cves"):
            lines.append(f"- Known CVEs: {', '.join(ssh['known_cves'])}")
        lines.append("")

    mysql = scan_result.get("mysql", {})
    if mysql.get("enabled"):
        lines += [
            "### MySQL",
            f"- Accessible: **{'YES ⚠️' if mysql.get('accessible') else 'NO'}**",
        ]
        if mysql.get("credentials_found"):
            lines.append(f"- Credentials: `{mysql['credentials_found']}`")
        lines.append("")

    smb = scan_result.get("smb", {})
    if smb.get("enabled"):
        lines += [
            "### SMB",
            f"- Null Session: **{'ALLOWED ⚠️' if smb.get('null_session') else 'DENIED'}**",
        ]
        if smb.get("shares"):
            shares_str = ", ".join(f"`{s['name']}`" for s in smb["shares"])
            lines.append(f"- Shares: {shares_str}")
        if smb.get("users"):
            lines.append(f"- Users: {', '.join(smb['users'][:10])}")
        lines.append("")

    # ── Web ────────────────────────────────────────────
    web = scan_result.get("web", {})
    if web.get("enabled"):
        lines += ["### Web Scanning", ""]
        nikto_findings = web.get("nikto", {}).get("findings", [])
        if nikto_findings:
            lines += [f"**Nikto Findings ({len(nikto_findings)}):**", ""]
            for nf in nikto_findings[:20]:
                lines.append(f"- `{nf.get('path', '/')}` — {nf.get('description', '')}")
            lines.append("")
        gobuster_paths = web.get("gobuster", {}).get("paths", [])
        if gobuster_paths:
            paths_str = ", ".join(f"`{p['path']}`" for p in gobuster_paths[:20])
            lines += [f"**Discovered Paths ({len(gobuster_paths)}):** {paths_str}", ""]

    # ── Footer ─────────────────────────────────────────
    lines += [
        "---",
        "",
        "*Generated by [AEGIS](https://github.com/username/aegis) v1.0 — For authorized lab use only.*",
        "",
    ]

    # Write file
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"Markdown report saved: {output_path}")
    return output_path
