"""
core/setup_wizard.py — Interactive AEGIS setup wizard

Run with: python aegis.py setup

Guides the user through configuring their OpenRouter API key,
saves it to a .env file, and optionally tests the connection.
"""

import os
import sys
import logging
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich import box
from rich.table import Table
from rich.text import Text

logger = logging.getLogger("aegis")

ENV_FILE = Path(".env")
ENV_EXAMPLE_FILE = Path(".env.example")

# All configurable keys with their defaults and descriptions
CONFIG_SCHEMA = [
    {
        "key": "OPENROUTER_API_KEY",
        "label": "OpenRouter API Key",
        "default": "",
        "secret": True,
        "required": True,
        "hint": "Get yours free at https://openrouter.ai/keys",
        "validate": lambda v: v.startswith("sk-or-") if v else False,
        "validate_msg": "OpenRouter keys start with 'sk-or-'. Please check and try again.",
    },
    {
        "key": "AEGIS_MODEL",
        "label": "LLM Model",
        "default": "qwen/qwen2.5-72b-instruct",
        "secret": False,
        "required": False,
        "hint": "OpenRouter model ID. See https://openrouter.ai/models for options.",
        "validate": None,
    },
    {
        "key": "AEGIS_API_TIMEOUT",
        "label": "API Timeout (seconds)",
        "default": "60",
        "secret": False,
        "required": False,
        "hint": "Max wait time for AI response. Increase if you get timeouts.",
        "validate": lambda v: v.isdigit() and int(v) > 0,
        "validate_msg": "Must be a positive integer (e.g. 60).",
    },
    {
        "key": "AEGIS_API_RETRIES",
        "label": "API Retry Attempts",
        "default": "3",
        "secret": False,
        "required": False,
        "hint": "How many times to retry on API errors.",
        "validate": lambda v: v.isdigit() and int(v) > 0,
        "validate_msg": "Must be a positive integer (e.g. 3).",
    },
    {
        "key": "AEGIS_REPORTS_DIR",
        "label": "Reports Directory",
        "default": "./reports",
        "secret": False,
        "required": False,
        "hint": "Where to save generated scan reports.",
        "validate": None,
    },
    {
        "key": "AEGIS_WORDLIST",
        "label": "Gobuster Wordlist Path",
        "default": "/usr/share/wordlists/dirb/common.txt",
        "secret": False,
        "required": False,
        "hint": "Path to wordlist for directory enumeration. Install: sudo apt install dirb",
        "validate": None,
    },
    {
        "key": "AEGIS_NMAP_TIMEOUT",
        "label": "Nmap Timeout (seconds)",
        "default": "600",
        "secret": False,
        "required": False,
        "hint": "Max wait for nmap scans. Full port scans can take several minutes.",
        "validate": lambda v: v.isdigit() and int(v) > 0,
        "validate_msg": "Must be a positive integer (e.g. 600).",
    },
    {
        "key": "AEGIS_DEBUG",
        "label": "Debug Logging",
        "default": "false",
        "secret": False,
        "required": False,
        "hint": "Set to 'true' to enable verbose debug logging to aegis.log.",
        "validate": lambda v: v.lower() in ("true", "false"),
        "validate_msg": "Must be 'true' or 'false'.",
    },
]


def _load_existing_env() -> dict:
    """Read existing .env file into a dict."""
    env = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def _write_env(config: dict) -> None:
    """Write config dict to .env file."""
    lines = [
        "# AEGIS Configuration — generated by 'python aegis.py setup'",
        "# DO NOT commit this file to version control.",
        "",
    ]
    for key, value in config.items():
        lines.append(f'{key}="{value}"')

    with open(ENV_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _mask_secret(value: str) -> str:
    """Mask all but last 4 chars of a secret value."""
    if not value or len(value) <= 4:
        return "****"
    return "*" * (len(value) - 4) + value[-4:]


def run_setup() -> None:
    """
    Interactive setup wizard. Writes configuration to .env.
    """
    console = Console()

    # ── Welcome Banner ───────────────────────────────────
    console.print(
        Panel(
            "[bold cyan]AEGIS Setup Wizard[/bold cyan]\n\n"
            "This wizard will configure AEGIS and save your settings to [bold].env[/bold].\n\n"
            "[dim]Press Enter to accept defaults shown in brackets.[/dim]\n"
            "[dim]Your API key is stored locally and never shared.[/dim]",
            title="[bold white][ AEGIS ] Configuration Setup[/bold white]",
            border_style="cyan",
            padding=(1, 2),
        )
    )
    console.print()

    # ── Load existing config ─────────────────────────────
    existing = _load_existing_env()
    if existing:
        console.print(
            f"  [bold yellow]ℹ[/bold yellow]  "
            f"[yellow]Found existing .env with {len(existing)} setting(s). "
            f"Press Enter to keep current values.[/yellow]\n"
        )

    # ── Collect settings ─────────────────────────────────
    new_config = {}

    for field in CONFIG_SCHEMA:
        key = field["key"]
        label = field["label"]
        default = existing.get(key, field["default"])
        secret = field["secret"]
        hint = field["hint"]
        required = field["required"]
        validator = field.get("validate")
        validate_msg = field.get("validate_msg", "Invalid value.")

        console.print(f"  [bold white]{label}[/bold white]")
        console.print(f"  [dim]{hint}[/dim]")

        display_default = _mask_secret(default) if (secret and default) else (default or "")

        while True:
            if secret:
                value = Prompt.ask(
                    f"  [cyan]{key}[/cyan]",
                    default=display_default if default else "",
                    password=True,
                    console=console,
                )
                # If user hit Enter and there's an existing value, keep it
                if value == display_default and default:
                    value = default
                elif not value and default:
                    value = default
            else:
                value = Prompt.ask(
                    f"  [cyan]{key}[/cyan]",
                    default=default or "",
                    console=console,
                )

            # Validate
            if required and not value:
                console.print(f"  [bold red]✗[/bold red]  [red]This field is required.[/red]")
                continue

            if value and validator:
                try:
                    if not validator(value):
                        console.print(f"  [bold red]✗[/bold red]  [red]{validate_msg}[/red]")
                        continue
                except Exception:
                    console.print(f"  [bold red]✗[/bold red]  [red]{validate_msg}[/red]")
                    continue

            new_config[key] = value
            break

        console.print()

    # ── Test API connection ──────────────────────────────
    api_key = new_config.get("OPENROUTER_API_KEY", "")
    if api_key:
        should_test = Confirm.ask(
            "  [bold cyan]Test OpenRouter API connection now?[/bold cyan]",
            default=True,
            console=console,
        )
        if should_test:
            console.print("  [dim]Connecting to OpenRouter...[/dim]")
            try:
                # Temporarily set the env var for the test
                os.environ["OPENROUTER_API_KEY"] = api_key
                os.environ["AEGIS_MODEL"] = new_config.get(
                    "AEGIS_MODEL", "qwen/qwen2.5-72b-instruct"
                )
                from ai.intelligence import test_api_connection
                success, message = test_api_connection(api_key)
            except Exception as e:
                success, message = False, f"Test error: {str(e)}"

            if success:
                console.print(
                    f"  [bold green]✓[/bold green]  [green]{message}[/green]\n"
                )
            else:
                console.print(
                    f"  [bold red]✗[/bold red]  [red]{message}[/red]\n"
                )
                if not Confirm.ask(
                    "  [yellow]Save settings anyway?[/yellow]",
                    default=False,
                    console=console,
                ):
                    console.print("  [dim]Setup cancelled. No changes saved.[/dim]")
                    return

    # ── Write .env ───────────────────────────────────────
    _write_env(new_config)

    # ── Summary table ────────────────────────────────────
    console.print()
    table = Table(
        title="Configuration Saved",
        box=box.ROUNDED,
        title_style="bold green",
        header_style="bold white",
        show_lines=True,
    )
    table.add_column("Setting", style="bold white", width=28)
    table.add_column("Value", width=45)

    for field in CONFIG_SCHEMA:
        key = field["key"]
        value = new_config.get(key, "")
        display = _mask_secret(value) if field["secret"] and value else (value or "[dim]not set[/dim]")
        table.add_row(key, display)

    console.print(table)

    console.print(
        Panel(
            f"[bold green]✓ Configuration saved to [white].env[/white][/bold green]\n\n"
            "[white]You can now run AEGIS:[/white]\n\n"
            "[cyan]  python aegis.py --target 192.168.1.100[/cyan]\n\n"
            "[dim]Run 'python aegis.py setup' at any time to update settings.[/dim]",
            title="[bold green][ SETUP ] Complete[/bold green]",
            border_style="green",
            padding=(1, 2),
        )
    )


def show_current_config() -> None:
    """Display the current configuration from .env without allowing editing."""
    console = Console()
    existing = _load_existing_env()

    if not existing:
        console.print(
            Panel(
                "[yellow]No .env file found. Run 'python aegis.py setup' to configure AEGIS.[/yellow]",
                border_style="yellow",
            )
        )
        return

    table = Table(
        title="Current AEGIS Configuration (.env)",
        box=box.ROUNDED,
        title_style="bold cyan",
        header_style="bold white",
        show_lines=True,
    )
    table.add_column("Setting", style="bold white", width=28)
    table.add_column("Value", width=45)
    table.add_column("Status", width=12)

    all_required_set = True
    for field in CONFIG_SCHEMA:
        key = field["key"]
        value = existing.get(key, "")

        if field["secret"] and value:
            display = _mask_secret(value)
        else:
            display = value or "[dim]not set[/dim]"

        if field["required"] and not value:
            status = Text("MISSING", style="bold red")
            all_required_set = False
        elif value:
            status = Text("OK", style="bold green")
        else:
            status = Text("default", style="dim")

        table.add_row(key, display, status)

    console.print(table)

    if not all_required_set:
        console.print(
            "\n  [bold red]✗[/bold red]  "
            "[red]Required settings are missing. Run 'python aegis.py setup'.[/red]"
        )
